# move interface to enviroment
[enviroment]
webcapture_lib_path = '../webcapture'
interface = 'ens33'
store_path = './output' 

[meet-guest]

[meet-host]

[gg-search]

[gg-docs]


[gg-photos]

[gg-drive]


[youtube]


[amazon]


[shopee]


[tiktok]
url_list = ''

[helloworld-capture]
url_list = './common-res/youtube'
