# move interface to enviroment
[enviroment]
webcapture_lib_path = '../webcapture'
interface = 'ens33'
store_path = './output' 

[meet-guest]

[meet-host]

[gg-search]

[gg-docs]


[gg-photos]

[gg-drive]
url_list = './common-res/gdrive.csv'

[youtube]
url_list = './common-res/youtube.csv'

[youtubelive]
duration = 10

[amazon]
url_list = './common-res/amazon.csv'

[shopee]
url_list = './common-res/shopee.csv'

[lazada]

[tiki]

[thegioididong]

[ebay]

[tiktok]
url_list = ''

[helloworld-capture]
url_list = './common-res/youtube.csv'
