# move interface to enviroment
[enviroment]
interface = '' # Default to main
store_path = '~/Desktop/rawpcap'
profile_path = '/home/onos/Desktop/selenium-user' 

# CRITICAL = 50
# FATAL = CRITICAL
# ERROR = 40
# WARNING = 30
# INFO = 20
# DEBUG = 10
# NOTSET = 0
log_level = 20

[meet-guest]

[meet-host]

[gg-search]

[gg-docs]


[gg-photos]

[gg-drive]
url_list = './common-res/gdrive.csv'

[youtube]
url_list = './common-res/youtube.csv'
playlist = './common-res/youtube-playlist.csv'

[youtubelive]
duration = 1800
# duration = 10

[amazon]
url_list = './common-res/amazon.csv'

[shopee]
url_list = './common-res/shopee.csv'

[lazada]
url_list = './common-res/lazada.csv'

[tiki]
url_list = './common-res/tiki.csv'

[thegioididong]
url_list = './common-res/thegioididong.csv'
min_page = 25
max_page = 150

[ebay]
url_list = './common-res/ebay.csv'

[tiktok]
url_list = './common-res/tiktok.csv'

[helloworld-capture]
url_list = './common-res/youtube.csv'
