# move interface to enviroment
[enviroment]
webcapture_lib_path = '../webcapture'
interface = ''

[meet-guest]

[meet-host]

[gg-search]

[gg-docs]


[gg-photos]

[gg-drive]


[youtube]


[amazon]


[shopee]


[tiktok]


[test-capture]
interface = 'ens33'